name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test API
        run: |
          cd api
          dotnet build
          dotnet test

      - name: Build and test Webapp
        run: |
          cd webapp
          npm install
          npm run build
          npm test

      - name: Deploy API to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ vars.HEROKU_APP_NAME_API }}
          heroku_email: ${{ vars.HEROKU_EMAIL }}
          usedocker: true

      - name: Deploy API to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ vars.HEROKU_APP_NAME_WEBAPP }}
          heroku_email: ${{ vars.HEROKU_EMAIL }}
          usedocker: true
